# Generated by Django 5.2.7 on 2025-12-26 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('region', models.CharField(max_length=100, verbose_name='Bölge')),
                ('altitude', models.IntegerField(default=0, verbose_name='Rakım (m)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IrisPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.FloatField(verbose_name='Sepal Length (cm)')),
                ('sepal_width', models.FloatField(verbose_name='Sepal Width (cm)')),
                ('petal_length', models.FloatField(verbose_name='Petal Length (cm)')),
                ('petal_width', models.FloatField(verbose_name='Petal Width (cm)')),
                ('species', models.CharField(choices=[('Iris-setosa', 'Iris-setosa'), ('Iris-versicolor', 'Iris-versicolor'), ('Iris-virginica', 'Iris-virginica')], max_length=20, verbose_name='Tür')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='iris_app.location', verbose_name='Konum')),
            ],
        ),
    ]
