# Generated by Django 5.2.7 on 2025-12-26 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irisplant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='iris_app.location', verbose_name='Konum'),
        ),
        migrations.AlterField(
            model_name='irisplant',
            name='species',
            field=models.CharField(max_length=50, verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bölge'),
        ),
    ]
